// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9VvUAqeI7wQd9-LvM5BLYPTM5nPRWGmg',
    appId: '1:217098805414:web:f6bc6e859d908623775467',
    messagingSenderId: '217098805414',
    projectId: 'morningstarr',
    authDomain: 'morningstarr.firebaseapp.com',
    storageBucket: 'morningstarr.appspot.com',
    measurementId: 'G-1VDB01606X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlAyWxpCGvP5G5bHQBul3X_ziqJdKYYHU',
    appId: '1:217098805414:android:7d491426e1d506d7775467',
    messagingSenderId: '217098805414',
    projectId: 'morningstarr',
    storageBucket: 'morningstarr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiHUsYF2RGoHjTAbTi2SO7QwBGZxkBilE',
    appId: '1:217098805414:ios:d44b1efe5d14eee3775467',
    messagingSenderId: '217098805414',
    projectId: 'morningstarr',
    storageBucket: 'morningstarr.appspot.com',
    iosBundleId: 'com.example.morningstar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiHUsYF2RGoHjTAbTi2SO7QwBGZxkBilE',
    appId: '1:217098805414:ios:d44b1efe5d14eee3775467',
    messagingSenderId: '217098805414',
    projectId: 'morningstarr',
    storageBucket: 'morningstarr.appspot.com',
    iosBundleId: 'com.example.morningstar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9VvUAqeI7wQd9-LvM5BLYPTM5nPRWGmg',
    appId: '1:217098805414:web:ac31afd5951ad9bb775467',
    messagingSenderId: '217098805414',
    projectId: 'morningstarr',
    authDomain: 'morningstarr.firebaseapp.com',
    storageBucket: 'morningstarr.appspot.com',
    measurementId: 'G-8SWE0SFG7B',
  );
}
